name: CI

on: [push]

env:
  ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}

jobs:
  cypress-and-argos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Install Gatsby CLI
        run: yarn add -D gatsby-cli

      # - name: Build plugins
      #   run: cd plugins/argos-javascript && yarn install --prefer-offline --frozen-lockfile && yarn build

      - name: Build
        run: yarn build
