name: CI

on: [push]

jobs:
  cypress-and-argos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install plugins dependencies
        run: yarn --cwd "plugins/argos-javascript" --prefer-offline --frozen-lockfile

      # - name: Build plugins
      #   run: yarn build-plugins

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Install Gatsby CLI
        run: yarn add -D gatsby-cli

      - name: Build
        run: yarn build
